# Generated by Django 3.0.8 on 2020-07-27 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_product_slug'), ('main', '0003_auto_20200727_1341'), ('main', '0004_auto_20200727_1410'), ('main', '0005_auto_20200727_1517'), ('main', '0006_remove_specification_print')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('short_descr', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('full_descr', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('specific', models.TextField(verbose_name='Характеристики')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, verbose_name='Размеры')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('material', models.CharField(max_length=150, verbose_name='Материал')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товаров',
            },
        ),
    ]
