# Generated by Django 3.0.8 on 2020-07-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200727_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='title',
        ),
        migrations.AddField(
            model_name='specification',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='print',
            field=models.BooleanField(verbose_name='Рисунок'),
        ),
    ]
