# Generated by Django 3.0.8 on 2020-07-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200727_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='print',
        ),
    ]
